/* Populate Tables*/
INSERT INTO usuarios (nombre, apellido, usuario, email, create_at, fecha_nacimiento, contrasenia, direccion, saldo, edad, estado) VALUES('Andres', 'Guzman', 'AGuzman','profesor@bolsadeideas.com','2019-06-25', '2017-08-01', 'password', 'Reino de Liones', 20, 40, true);
INSERT INTO usuarios (nombre,apellido,usuario,email,create_at,fecha_nacimiento,contrasenia,direccion,saldo,edad,estado) VALUES ('Iris','Mckinney','Jemima','dolor.egestas@interdum.edu','2019-06-25','2017-08-01','BQF84BOD2ZW','Ap #859-4532 Congue Street',8,26,'true');
INSERT INTO usuarios (nombre, apellido, usuario, email, create_at, fecha_nacimiento, contrasenia, direccion, saldo, edad, estado) VALUES('Andres', 'Guzman', 'AGuzman','profesor@bolsadeideas.com','2019-06-25', '2017-08-01', 'password', 'Reino de Liones', 20, 40, true);
INSERT INTO usuarios (nombre,apellido,usuario,email,create_at,fecha_nacimiento,contrasenia,direccion,saldo,edad,estado) VALUES ('Iris','Mckinney','Jemima','dolor.egestas@interdum.edu','2019-06-25','2017-08-01','BQF84BOD2ZW','Ap #859-4532 Congue Street',8,26,'true');
INSERT INTO usuarios (nombre, apellido, usuario, email, create_at, fecha_nacimiento, contrasenia, direccion, saldo, edad, estado) VALUES('Andres', 'Guzman', 'AGuzman','profesor@bolsadeideas.com','2019-06-25', '2017-08-01', 'password', 'Reino de Liones', 20, 40, true);
INSERT INTO usuarios (nombre,apellido,usuario,email,create_at,fecha_nacimiento,contrasenia,direccion,saldo,edad,estado) VALUES ('Iris','Mckinney','Jemima','dolor.egestas@interdum.edu','2019-06-25','2017-08-01','BQF84BOD2ZW','Ap #859-4532 Congue Street',8,26,'true');
INSERT INTO usuarios (nombre, apellido, usuario, email, create_at, fecha_nacimiento, contrasenia, direccion, saldo, edad, estado) VALUES('Andres', 'Guzman', 'AGuzman','profesor@bolsadeideas.com','2019-06-25', '2017-08-01', 'password', 'Reino de Liones', 20, 40, true);
INSERT INTO usuarios (nombre,apellido,usuario,email,create_at,fecha_nacimiento,contrasenia,direccion,saldo,edad,estado) VALUES ('Iris','Mckinney','Jemima','dolor.egestas@interdum.edu','2019-06-25','2017-08-01','BQF84BOD2ZW','Ap #859-4532 Congue Street',8,26,'true');
INSERT INTO usuarios (nombre, apellido, usuario, email, create_at, fecha_nacimiento, contrasenia, direccion, saldo, edad, estado) VALUES('Andres', 'Guzman', 'AGuzman','profesor@bolsadeideas.com','2019-06-25', '2017-08-01', 'password', 'Reino de Liones', 20, 40, true);
INSERT INTO usuarios (nombre,apellido,usuario,email,create_at,fecha_nacimiento,contrasenia,direccion,saldo,edad,estado) VALUES ('Iris','Mckinney','Jemima','dolor.egestas@interdum.edu','2019-06-25','2017-08-01','BQF84BOD2ZW','Ap #859-4532 Congue Street',8,26,'true');
INSERT INTO usuarios (nombre, apellido, usuario, email, create_at, fecha_nacimiento, contrasenia, direccion, saldo, edad, estado) VALUES('Andres', 'Guzman', 'AGuzman','profesor@bolsadeideas.com','2019-06-25', '2017-08-01', 'password', 'Reino de Liones', 20, 40, true);
INSERT INTO usuarios (nombre,apellido,usuario,email,create_at,fecha_nacimiento,contrasenia,direccion,saldo,edad,estado) VALUES ('Iris','Mckinney','Jemima','dolor.egestas@interdum.edu','2019-06-25','2017-08-01','BQF84BOD2ZW','Ap #859-4532 Congue Street',8,26,'true');
INSERT INTO usuarios (nombre, apellido, usuario, email, create_at, fecha_nacimiento, contrasenia, direccion, saldo, edad, estado) VALUES('Andres', 'Guzman', 'AGuzman','profesor@bolsadeideas.com','2019-06-25', '2017-08-01', 'password', 'Reino de Liones', 20, 40, true);
INSERT INTO usuarios (nombre,apellido,usuario,email,create_at,fecha_nacimiento,contrasenia,direccion,saldo,edad,estado) VALUES ('Iris','Mckinney','Jemima','dolor.egestas@interdum.edu','2019-06-25','2017-08-01','BQF84BOD2ZW','Ap #859-4532 Congue Street',8,26,'true');

INSERT INTO peliculas(nombre,duracion,estreno,genero,formato,idioma,estado,create_at) VALUES ('Titanic','1:30',true,'Drama','3D','Español',true,'1997-06-30');